-- Content lives in relational columns. NULL represents an absent optional field.
CREATE TABLE workspace_metadata (
 id SMALLINT PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL CHECK(version=2),
 catalog_version INTEGER CHECK(catalog_version=1), journals_version INTEGER CHECK(journals_version=2),
 personal_journal_present BOOLEAN NOT NULL, goals_present BOOLEAN NOT NULL,
 change_sequence BIGINT NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE SEQUENCE entity_position;
CREATE TABLE notes (id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 200 AND id ~ '^[a-zA-Z0-9_/-]+$'), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200), description TEXT NOT NULL CHECK(length(description)<=1000), tags TEXT[] NOT NULL CHECK(cardinality(tags)<=30), body TEXT NOT NULL CHECK(length(body)<=100000), revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position >= 0), updated_at TIMESTAMPTZ, topic TEXT NOT NULL CHECK(length(topic) BETWEEN 1 AND 100));
CREATE TABLE documents (id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 200 AND id ~ '^[a-zA-Z0-9_/-]+$'), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200), description TEXT NOT NULL CHECK(length(description)<=1000), tags TEXT[] NOT NULL CHECK(cardinality(tags)<=30), body TEXT NOT NULL CHECK(length(body)<=100000), revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position >= 0), updated_at TIMESTAMPTZ, is_core BOOLEAN NOT NULL);
CREATE TABLE personal_journal_entries (id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 200 AND id ~ '^[a-zA-Z0-9_/-]+$'), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200), description TEXT NOT NULL CHECK(length(description)<=1000), tags TEXT[] NOT NULL CHECK(cardinality(tags)<=30), body TEXT NOT NULL CHECK(length(body)<=100000), revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position >= 0), updated_at TIMESTAMPTZ, entry_date DATE);
CREATE TABLE journal_weeks (slug TEXT PRIMARY KEY CHECK(length(slug) BETWEEN 1 AND 200 AND slug ~ '^[a-zA-Z0-9_/-]+$'), week INTEGER NOT NULL CHECK(week BETWEEN 1 AND 10000), year INTEGER NOT NULL CHECK(year BETWEEN 2000 AND 2200), dates TEXT NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, tags TEXT[] NOT NULL CHECK(cardinality(tags)<=30), body TEXT NOT NULL CHECK(length(body)<=100000), targets_present BOOLEAN NOT NULL, revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position >= 0), updated_at TIMESTAMPTZ, CHECK(end_date>=start_date));
CREATE TABLE journal_week_metrics (week_slug TEXT REFERENCES journal_weeks(slug) ON DELETE CASCADE, track TEXT CHECK(length(track)<=80), hours NUMERIC CHECK(hours BETWEEN 0 AND 168), target NUMERIC CHECK(target BETWEEN 0 AND 168), PRIMARY KEY(week_slug,track), CHECK(hours IS NOT NULL OR target IS NOT NULL));
CREATE TABLE books (slug TEXT PRIMARY KEY CHECK(length(slug) BETWEEN 1 AND 200 AND slug ~ '^[a-zA-Z0-9_/-]+$'), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200), category TEXT NOT NULL, type TEXT NOT NULL, url TEXT, cover TEXT, status TEXT NOT NULL, featured BOOLEAN NOT NULL, priority TEXT NOT NULL CHECK(priority IN ('high','medium','low')), tags TEXT[] NOT NULL CHECK(cardinality(tags)<=30), body TEXT NOT NULL CHECK(length(body)<=100000), revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position >= 0), updated_at TIMESTAMPTZ, edition TEXT, authors TEXT[] NOT NULL CHECK(cardinality(authors)<=30), isbn TEXT, started DATE, finished DATE, rating NUMERIC CHECK(rating BETWEEN 0 AND 5), progress_unit TEXT CHECK(progress_unit IN ('chapter','page','module','section','lecture')), progress_total INTEGER CHECK(progress_total BETWEEN 0 AND 100000), progress_completed INTEGER CHECK(progress_completed BETWEEN 0 AND progress_total), CHECK(num_nonnulls(progress_unit,progress_total,progress_completed) IN (0,3)), CHECK(type IN ('book','course')), CHECK(status IN ('backlog','reading','paused','completed','reference')), CHECK(category IN ('Computer Science','Networking','OS','Systems','Distributed Systems','Languages','Career','Online Course')));
CREATE TABLE companies (slug TEXT PRIMARY KEY CHECK(length(slug) BETWEEN 1 AND 200 AND slug ~ '^[a-zA-Z0-9_/-]+$'), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200), category TEXT NOT NULL, type TEXT NOT NULL, url TEXT, cover TEXT, status TEXT NOT NULL, featured BOOLEAN NOT NULL, priority TEXT NOT NULL CHECK(priority IN ('high','medium','low')), tags TEXT[] NOT NULL CHECK(cardinality(tags)<=30), body TEXT NOT NULL CHECK(length(body)<=100000), revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position >= 0), updated_at TIMESTAMPTZ, contacts_present BOOLEAN NOT NULL, CHECK(type='company'), CHECK(url IS NOT NULL), CHECK(status IN ('not_started','applied','interviewing','offer','rejected','passed')));
CREATE TABLE company_contacts (company_slug TEXT REFERENCES companies(slug) ON DELETE CASCADE, id UUID, position INTEGER NOT NULL CHECK(position>=0), name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 200), role TEXT NOT NULL CHECK(length(role)<=200), email TEXT NOT NULL CHECK(length(email)<=254), url TEXT NOT NULL, notes TEXT NOT NULL CHECK(length(notes)<=5000), PRIMARY KEY(company_slug,id), UNIQUE(company_slug,position));
CREATE TABLE goals (id UUID PRIMARY KEY, title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200), start_date DATE NOT NULL CHECK(start_date BETWEEN '1900-01-01' AND '2200-12-31'), end_date DATE NOT NULL CHECK(end_date BETWEEN start_date AND '2200-12-31'), color TEXT NOT NULL CHECK(color ~ '^#[0-9a-fA-F]{6}$'), daily_hours NUMERIC CHECK(daily_hours BETWEEN 0 AND 24), created_at TIMESTAMPTZ NOT NULL, revision TEXT NOT NULL, position BIGINT NOT NULL CHECK(position>=0), updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE goal_notes (goal_id UUID REFERENCES goals(id) ON DELETE CASCADE, id UUID, position INTEGER NOT NULL CHECK(position>=0), body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 20000), created_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(goal_id,id), UNIQUE(goal_id,position));
CREATE TABLE goal_steps (goal_id UUID REFERENCES goals(id) ON DELETE CASCADE, id UUID, position INTEGER NOT NULL CHECK(position>=0), title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 500), done BOOLEAN NOT NULL, PRIMARY KEY(goal_id,id), UNIQUE(goal_id,position));
CREATE TABLE goal_metadata (goal_id UUID REFERENCES goals(id) ON DELETE CASCADE, key TEXT CHECK(length(key) BETWEEN 1 AND 80), value TEXT NOT NULL CHECK(length(value)<=2000), PRIMARY KEY(goal_id,key));
CREATE TABLE migration_imports (id UUID PRIMARY KEY, source_store TEXT NOT NULL, source_key TEXT NOT NULL, source_revision TEXT, source_checksum TEXT NOT NULL, imported_at TIMESTAMPTZ NOT NULL DEFAULT now(), archive_path TEXT NOT NULL, version INTEGER NOT NULL, catalog_version INTEGER, journals_version INTEGER, UNIQUE(source_store,source_key,source_checksum));
-- Exact timestamp spellings are provenance, not a second content payload.
CREATE TABLE source_timestamps (kind TEXT NOT NULL, entity_id TEXT NOT NULL, field TEXT NOT NULL, value TEXT NOT NULL, PRIMARY KEY(kind,entity_id,field));
CREATE TABLE book_summaries (book_slug TEXT PRIMARY KEY REFERENCES books(slug) ON DELETE CASCADE, chapter_count INTEGER NOT NULL, completed_count INTEGER NOT NULL, excerpt TEXT NOT NULL, source_revision TEXT NOT NULL, parser_version INTEGER NOT NULL);
CREATE TABLE company_summaries (company_slug TEXT PRIMARY KEY REFERENCES companies(slug) ON DELETE CASCADE, why TEXT NOT NULL, step_count INTEGER NOT NULL, completed_count INTEGER NOT NULL, source_revision TEXT NOT NULL, parser_version INTEGER NOT NULL);
CREATE TABLE book_checklist (owner_slug TEXT REFERENCES books(slug) ON DELETE CASCADE, position INTEGER CHECK(position>=0), source_line INTEGER NOT NULL CHECK(source_line>=0), section TEXT NOT NULL, label TEXT NOT NULL, checked BOOLEAN NOT NULL, PRIMARY KEY(owner_slug,position));
CREATE TABLE book_logs (owner_slug TEXT REFERENCES books(slug) ON DELETE CASCADE, position INTEGER CHECK(position>=0), source_line INTEGER NOT NULL CHECK(source_line>=0), log_date TEXT, text TEXT NOT NULL, PRIMARY KEY(owner_slug,position));
CREATE TABLE company_checklist (owner_slug TEXT REFERENCES companies(slug) ON DELETE CASCADE, position INTEGER CHECK(position>=0), source_line INTEGER NOT NULL CHECK(source_line>=0), section TEXT NOT NULL, label TEXT NOT NULL, checked BOOLEAN NOT NULL, PRIMARY KEY(owner_slug,position));
CREATE TABLE company_logs (owner_slug TEXT REFERENCES companies(slug) ON DELETE CASCADE, position INTEGER CHECK(position>=0), source_line INTEGER NOT NULL CHECK(source_line>=0), log_date TEXT, text TEXT NOT NULL, PRIMARY KEY(owner_slug,position));
CREATE INDEX notes_topic_idx ON notes (topic,title,id);
CREATE INDEX documents_title_idx ON documents (title,id);
CREATE INDEX personal_journal_entries_entry_date_idx ON personal_journal_entries (entry_date DESC,id);
CREATE INDEX journal_weeks_start_date_idx ON journal_weeks (start_date DESC,slug);
CREATE INDEX journal_weeks_year_idx ON journal_weeks (year,week);
CREATE INDEX books_status_idx ON books (status,category,priority,slug);
CREATE INDEX companies_status_idx ON companies (status,category,priority,slug);
CREATE INDEX goals_start_date_idx ON goals (start_date,end_date);
