import { useState } from 'react';
import type { Settings } from '../lib/scheduler';
const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
export function WeeklySchedulerSettings({ settings, saving, save, close }: { settings: Settings; saving: boolean; save: (settings: Settings) => void; close: () => void }) {
  const [draft, setDraft] = useState(settings);
  const [date, setDate] = useState('');
  function interval(key: string, kind: 'defaultDay' | 'weekdays' | 'dates') {
    const value = kind === 'defaultDay' ? draft.defaultDay : draft[kind][key];
    if (!value) return null;
    const update = (patch: Partial<typeof value>) => setDraft(current => kind === 'defaultDay' ? { ...current, defaultDay: { ...value, ...patch } } : { ...current, [kind]: { ...current[kind], [key]: { ...value, ...patch } } });
    return <div className="scheduler-interval"><label>Start<input type="time" required value={value.start} onChange={e => update({ start: e.target.value })} /></label><label>End<input type="time" required value={value.end} onChange={e => update({ end: e.target.value })} /></label><label className="scheduler-check"><input type="checkbox" checked={value.nextDay} onChange={e => update({ nextDay: e.target.checked })} />Ends next day (equal times = full day)</label></div>;
  }
  return <section className="scheduler-panel" aria-label="Scheduler settings"><form onSubmit={e => { e.preventDefault(); save(draft); }}><h2>Day settings</h2><label>Time zone<input required value={draft.timeZone} placeholder="America/Chicago" onChange={e => setDraft({ ...draft, timeZone: e.target.value })} /></label><p>Use an IANA time zone. Date overrides take precedence over weekdays, then the default day. Existing historical times stay unchanged.</p><fieldset><legend>Default day</legend>{interval('', 'defaultDay')}</fieldset><details><summary>Weekday overrides</summary>{weekdays.map((name, index) => { const key = String(index + 1); return <fieldset key={key}><legend><label className="scheduler-check"><input type="checkbox" checked={Boolean(draft.weekdays[key])} onChange={e => { const values = { ...draft.weekdays }; if (e.target.checked) values[key] = { ...draft.defaultDay }; else delete values[key]; setDraft({ ...draft, weekdays: values }); }} />{name}</label></legend>{interval(key, 'weekdays')}</fieldset>; })}</details><details><summary>Date overrides</summary><div className="scheduler-actions"><label>Date<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><button type="button" disabled={!date} onClick={() => setDraft({ ...draft, dates: { ...draft.dates, [date]: { ...draft.defaultDay } } })}>Add override</button></div>{Object.keys(draft.dates).sort().map(key => <fieldset key={key}><legend>{key}</legend>{interval(key, 'dates')}<button type="button" onClick={() => { const values = { ...draft.dates }; delete values[key]; setDraft({ ...draft, dates: values }); }}>Remove override</button></fieldset>)}</details><div className="scheduler-actions"><button disabled={saving} type="submit">Save settings</button><button type="button" onClick={close}>Close</button></div></form></section>;
}
