import { useCallback, useEffect, useState } from 'react';
import { z } from 'zod';
import { schedulerRequest } from '../lib/scheduler';
const statusSchema = z.object({ configured: z.boolean(), connected: z.boolean(), reconnectRequired: z.boolean(), lastRefresh: z.string().nullish(), error: z.string().optional(), revision: z.string(), calendarId: z.string().optional() });
const calendarsSchema = z.object({ calendars: z.array(z.object({ id: z.string(), summary: z.string(), selected: z.boolean() })).nullable().transform(v => v ?? []), revision: z.string() });
export function WeeklySchedulerGoogle({ week, refreshWeek }: { week: string; refreshWeek: () => void }) {
  const [status, setStatus] = useState<z.infer<typeof statusSchema> | null>(null);
  const [calendars, setCalendars] = useState<z.infer<typeof calendarsSchema> | null>(null);
  const [error, setError] = useState('');
  const [working, setWorking] = useState(false);
  const readStatus = useCallback(async () => { setStatus(statusSchema.parse(await schedulerRequest('google/status'))); }, []);
  useEffect(() => { void readStatus().catch(e => setError(String(e))); }, [readStatus]);
  const perform = async (operation: () => Promise<void>) => { setWorking(true); setError(''); try { await operation(); await readStatus(); } catch (e) { setError(e instanceof Error ? e.message : 'Google request failed.'); } finally { setWorking(false); } };
  useEffect(() => {
    if (!status?.connected) return;
    const timer = window.setInterval(() => { if (document.visibilityState === 'visible') void schedulerRequest('google/refresh', { week }).then(() => { refreshWeek(); return readStatus(); }).catch(e => setError(String(e))); }, 300000);
    return () => clearInterval(timer);
  }, [week, status?.connected, refreshWeek, readStatus]);
  return <details className="scheduler-google"><summary>Google Calendar · {status?.reconnectRequired ? 'Reconnect needed' : status?.connected ? 'Connected' : 'Not connected'}</summary><p>Accepted plans sync to a dedicated calendar. Changes made in Google are restored from this app; actual-time corrections stay here. Disconnecting leaves exported events in Google.</p>{status?.lastRefresh && Date.parse(status.lastRefresh) > 0 && <p>Availability refreshed: {new Date(status.lastRefresh).toLocaleString()}</p>}{(error || status?.error) && <p role="alert">{error || status?.error}</p>}{status && !status.configured && <p>Google connection is not configured on this server. Local scheduling is available.</p>}<div className="scheduler-actions">{status?.configured && (!status.connected || status.reconnectRequired) && <button disabled={working} onClick={() => void perform(async () => { const result = z.object({ url: z.string().url() }).parse(await schedulerRequest('google/connect', {})); window.location.assign(result.url); })}>{status.reconnectRequired ? 'Reconnect Google' : 'Connect Google'}</button>}{status?.connected && <><button disabled={working} onClick={() => void perform(async () => { await schedulerRequest('google/refresh', { week }); refreshWeek(); })}>Refresh availability</button><button disabled={working} onClick={() => void perform(async () => setCalendars(calendarsSchema.parse(await schedulerRequest('google/calendars'))))}>Select busy calendars</button><button disabled={working} onClick={() => void perform(async () => { await schedulerRequest('google/disconnect', { revision: status.revision }); setCalendars(null); refreshWeek(); })}>Disconnect</button></>}</div>{calendars && <form onSubmit={e => { e.preventDefault(); void perform(async () => { await schedulerRequest('google/calendars', { revision: calendars.revision, calendarIds: calendars.calendars.filter(c => c.selected).map(c => c.id) }); setCalendars(null); refreshWeek(); }); }}>{calendars.calendars.map(calendar => <label className="scheduler-check" key={calendar.id}><input type="checkbox" checked={calendar.selected} onChange={e => setCalendars({ ...calendars, calendars: calendars.calendars.map(c => c.id === calendar.id ? { ...c, selected: e.target.checked } : c) })} />{calendar.summary}</label>)}<button disabled={working}>Save calendar selection</button></form>}</details>;
}
