#!/usr/bin/env node
// Explicit, single-week authoring helper; the UI creates entries on demand.
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { newWeek } from '../src/lib/workspace.ts';

const date = process.argv[2];
if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(Date.parse(date)) || new Date(date).toISOString().slice(0, 10) !== date || date < '2026-04-20' || date > '2199-12-31') {
  console.log('Use: npm run gen-weeks -- YYYY-MM-DD (2026-04-20 through 2199-12-31). No empty weeks are generated by default.');
  process.exit(date ? 1 : 0);
}
const week = newWeek(date);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const file = resolve(root, 'src/content/progress', `${week.slug}.md`);
if (existsSync(file)) {
  console.log(`Already exists: ${week.slug}`);
} else {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `---\nweek: ${week.week}\nyear: ${week.year}\ndates: "${week.dates}"\nhours: {}\ntags: []\n---\n\n${week.body}`);
  console.log(`Created ${week.slug}. Add content or logged hours before it is imported.`);
}
